Add half-working batch process control logic

diff --git a/bin/benchbot_batch b/bin/benchbot_batch
--- a/bin/benchbot_batch
+++ b/bin/benchbot_batch
@@ -138,6 +138,12 @@ FURTHER DETAILS:
         b.talbot@qut.edu.au
     "
 
+run_err="ERROR: Running of environment '%s' failed with the error printed above.
+Qutting batch execution."
+
+submission_err="ERROR: Submission for environment '%s' failed with the error printed
+above. Qutting batch execution."
+
 ################################################################################
 #################### Parse & handle command line arguments #####################
 ################################################################################
@@ -205,6 +211,8 @@ printf "$_ind%-25s%s\n$_ind" "Selected task:" "${task:-None}"
 if [[ $submit_args == "-c"* ]]; then
   printf "%-25s%s\n" "Dockerfile to build:" \
     "$(echo "$submit_args" | awk '{print $2}')/Dockerfile"
+elif [ -z "$submit_args" ]; then
+  printf "%-25s%s\n" "Command to execute:" "None"
 else
   printf "%-25s%s\n" "Command to execute:" \
     "$(echo "$submit_args" | awk '{for (i=2; i<=NF; i++) printf $i " "}')"
@@ -234,11 +242,41 @@ if [ -z "$envs_list" ]; then
 fi
 
 for i in "${!envs_list[@]}"; do
+  # Run the submission in the environment, waiting until something finishes
   header_block "Gathering results for environment: ${envs_list[$i]}" \
     $colour_magenta
-  # benchbot_run -t "$task" -e "${envs_list[$i]}" -f
-  # benchbot_submit -r "${prefix}_$i.json" 
-  touch "${prefix}_$i.json"
+  benchbot_run -t "${task:-None}" -e "${envs_list[$i]}" -f &> /tmp/benchbot_run_out &
+  run_pid=$!
+  benchbot_submit -r "${prefix}_$i.json" $submit_args &
+  submit_pid=$!
+  while ps -p $run_pid &>/dev/null && ps -p $submit_pid &>/dev/null; do
+    sleep 1
+  done
+
+  # Run should never die normally, so treat this as an error
+  if ! $(ps -p $run_pid &>/dev/null); then
+    kill -9 $submit_pid &> /dev/null
+    wait $submit_pid
+    printf "\n${colour_magenta}RUN COMMAND OUTPUT:${colour_nc}\n"
+    cat /tmp/benchbot_run_out
+    printf "\n$run_err\n" "${envs_list[$i]}"
+    exit 1
+  fi
+
+  # Handle the result of failed submissions (looking for an error code)
+  wait $submit_pid
+  submit_result=$?
+  echo "SUBMIT IS DONE~?@?#"
+  if [ $submit_result -ne 0 ]; then
+    kill -9 $run_pid &> /dev/null
+    wait $run_pid
+    printf "\n$submission_err\n" "${envs_list[$i]}"
+    exit 1
+  fi
+
+  # All is well if we made it here (submit finished naturally)
+  kill -9 $run_pid &>/dev/null
+  wait $run_pid
 done
 
 ################################################################################
@@ -248,10 +286,14 @@ done
 header_block "Processing results from batch" $colour_magenta
 
 if [ ! -z "$zip" ]; then
-  echo "Zipping up results ..."
-  touch "${prefix}_scores.zip"
+  echo "Zipping up results ... "
+  rm -vf "${prefix}.zip" && zip "${prefix}.zip" "${prefix}_"[0-9]*.json
+  echo -e "Done\n"
 fi
 
 if [ ! -z "$evaluate" ]; then
   echo "Evaluating results..."
+  touch "${prefix}_scores.json"
 fi
+
+echo "Done."
