Handle batches properly in benchbot_eval

diff --git a/bin/benchbot_eval b/bin/benchbot_eval
--- a/bin/benchbot_eval
+++ b/bin/benchbot_eval
@@ -170,11 +170,13 @@ function validate_method() {
 }
 
 function validate_required_envs() {
-  # $1 required envs, $2 required envs file
-  if [ ! -z "$required_envs" ] && [ ! -z "$required_envs_file" ]; then
+  # $1 required envs, $2 required envs batch
+  if [ ! -z "$1" ] && [ ! -z "$2" ]; then
     printf "${colour_red}%s %s${colour_nc}\n" \
-      "ERROR: Only '--required-envs' or '--required-envs-file' is valid,"\
+      "ERROR: Only '--required-envs' or '--required-envs-batch' is valid,"\
       "not both."
+  elif [ ! -z "$2" ]; then
+    validate_content "batches" "$2" "" "" 2
   fi
 }
 
@@ -206,7 +208,7 @@ function validate_results_files() {
 
 # Safely parse options input
 _args='help,list-batches,list-methods,method:,output-location:,\
-required-envs:,required-env-batch:,required-task:,show-batch:,\
+required-envs:,required-envs-batch:,required-task:,show-batch:,\
 show-method:,validate-only,version'
 parse_out=$(getopt -o ho:m:vV --long "$_args" -n "$(basename "$0")" -- "$@")
 if [ $? != 0 ]; then exit 1; fi
@@ -232,12 +234,12 @@ while true; do
       scores_location="$2"; shift 2 ;;
     --required-envs)
       required_envs=($(echo "$2" | tr ',' '\n')); shift 2 ;;
-    --required-env-batch)
+    --required-envs-batch)
       required_envs_batch="$2"; shift 2 ;;
     --required-task)
       required_task="$2"; shift 2 ;;
     --show-batch)
-      show_content "batches" "$2"; exit $? ;;
+      show_content "batches" "$2" 2; exit $? ;;
     --show-method)
       show_content "evaluation_methods" "$2"; exit $? ;;
     -v|--version)
@@ -252,10 +254,11 @@ while true; do
 done
 
 # Bail if any of the requested configurations are invalid
-err="$(validate_required_envs "$required_envs" "$required_envs_file")"
+err="$(validate_required_envs "$required_envs" "$required_envs_batch")"
 if [ ! -z "$err" ]; then echo "$err"; exit 1; fi
-if [ ! -z "$required_envs_file" ]; then
-  required_envs=($(cat "$required_envs_file" | sed 's/[[:space:]]*$//'))
+if [ ! -z "$required_envs_batch" ]; then
+  required_envs=($(run_manager_cmd 'print("\n".join(get_value_by_name(\
+    "batches", "'$required_envs_batch'", "environments")))'))
 fi
 if [ ! -z "$required_envs" ]; then
   for e in "${required_envs[@]}"; do
