Improve early exit handling of benchbot_submit

diff --git a/bin/benchbot_submit b/bin/benchbot_submit
--- a/bin/benchbot_submit
+++ b/bin/benchbot_submit
@@ -158,8 +158,16 @@ function expand_mode() {
   fi
 }
 
-function remove_submission_container() {
-  # $1 mode (expanded)
+active_pid=
+function exit_gracefully() {
+  # $1 mode, $2 exit code
+
+  # Pass the signal to the currently running process
+  if [ ! -z "$active_pid" ]; then
+    kill -TERM $active_pid &> /dev/null
+    wait $active_pid || true
+    active_pid=
+  fi
   
   # Cleanup containers if we ran in containerised mode
   if [[ "$1" == c* ]]; then
@@ -167,6 +175,8 @@ function remove_submission_container() {
     header_block "Cleaning up user containers" ${colour_blue}
     docker system prune -f  # TODO this is probably too brutal
   fi
+
+  exit ${2:-0}
 }
 
 function submission_command() {
@@ -353,7 +363,8 @@ echo ""
 
 # Actually perform the submission
 header_block "Running submission in '$mode' mode" ${colour_green}
-trap 'remove_submission_container "'$mode'"' EXIT
+
+trap "exit_gracefully $mode"  SIGINT SIGQUIT SIGKILL SIGTERM
 
 # Clear out any previous results in default location
 results_src=
@@ -369,7 +380,9 @@ if [ "$mode" == "native" ]; then
   # This is native submission mode
   echo -e \
     "Running submission natively via command:\n\t'$config_cmd' ...\n"
-  eval "$config_cmd" && run_ret=0 || run_ret=1
+  eval "$config_cmd" && run_ret=0 || run_ret=1 &
+  active_pid=$!
+  wait $active_pid
 elif [ "$mode" == "submission" ]; then
   # This is bundling up submission mode
   echo -e "Bundling up submission from '$config_dir' ...\n"
@@ -382,9 +395,11 @@ else
   echo "Running submission from '$config_dir' with containerisation ..."
   pushd "$config_dir" >/dev/null
   submission_tag="benchbot/submission:"$(echo "$(pwd)" | sha256sum | cut -c1-10)
-  docker build -t "$submission_tag" . && run_ret=0 || run_ret=1
+  docker build -t "$submission_tag" . && run_ret=0 || run_ret=1 &
+  active_pid=$!
+  wait $active_pid
   if [ $run_ret -ne 0 ]; then
-    echo "Docker build returned a non-zero error code: $build_ret"
+    echo "Docker build returned a non-zero error code: $run_ret"
   else
     xhost +local:root
     docker run --gpus all -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY \
